# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.cache/wt [current_project]
set_property parent.project_path C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/new/data_sync.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/new/decodificador_7s.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/Desktop/uart_tx.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/new/uart_rx.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/Desktop/uart_baud_tick_gen.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/new/ALU.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/Downloads/unsigned_to_bcd.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/new/UART_TX_CTRL.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/new/driver_display7seg.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/imports/Desktop/uart_basic.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/new/UART_RX_CTRL.v
  C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/sources_1/new/top_modulept2.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Gerson/Documents/ELO212/LAB_5/LAB_5/LAB_5.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]


synth_design -top top_modulept2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_modulept2.dcp

catch { report_utilization -file top_modulept2_utilization_synth.rpt -pb top_modulept2_utilization_synth.pb }
