# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo.xci
# IP: The module: 'clk_nuevo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_nuevo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_nuevo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_nuevo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo.xci
# IP: The module: 'clk_nuevo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_nuevo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_nuevo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Diego/LabDigitales2017/Lab_Saleae_1.0/Lab_Saleae_1.0.srcs/sources_1/ip/clk_nuevo/clk_nuevo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_nuevo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
