# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/GitHub/LabDigitales2017/project_example/project_example.cache/wt [current_project]
set_property parent.project_path C:/GitHub/LabDigitales2017/project_example/project_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/GitHub/LabDigitales2017/project_example/project_example.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/bcd_to_ss.v
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/unsigned_to_bcd.v
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/ss_mux.v
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/clk_divider.v
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/ejemplo_sensor_de_temperatura.v
}
read_vhdl -library xil_defaultlib {
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/TWICtl.vhd
  C:/GitHub/LabDigitales2017/project_example/project_example.srcs/sources_1/imports/ejemplo_temperatura_en_display/TempSensorCtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/GitHub/LabDigitales2017/project_example/project_example.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}
set_property used_in_implementation false [get_files {{C:/GitHub/LabDigitales2017/project_example/project_example.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}]


synth_design -top ejemplo_sensor_de_temperatura -part xc7a100tcsg324-1


write_checkpoint -force -noxdef ejemplo_sensor_de_temperatura.dcp

catch { report_utilization -file ejemplo_sensor_de_temperatura_utilization_synth.rpt -pb ejemplo_sensor_de_temperatura_utilization_synth.pb }
