# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/GitHub/LabDigitales2017/Final_Project/Final_Project.cache/wt [current_project]
set_property parent.project_path C:/GitHub/LabDigitales2017/Final_Project/Final_Project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/GitHub/LabDigitales2017/Final_Project/Final_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/new/translate.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/Lab6_PS2_VGA_reference/characters.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/new/cursor.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/Downloads/take_sample.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/new/Grafico_Diego.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/Lab6_PS2_VGA_reference/templates.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/Lab6_PS2_VGA_reference/hello_world.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/Lab6_PS2_VGA_reference/driver_vga.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/Lab6_PS2_VGA_reference/kbd_ms.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/new/Interfaz_Seba.v
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/new/Final_Project.v
}
read_vhdl -library xil_defaultlib {
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/ejemplo_temperatura_en_display/TWICtl.vhd
  C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/sources_1/imports/ejemplo_temperatura_en_display/TempSensorCtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}
set_property used_in_implementation false [get_files {{C:/GitHub/LabDigitales2017/Final_Project/Final_Project.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}]


synth_design -top Final_Project -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Final_Project.dcp

catch { report_utilization -file Final_Project_utilization_synth.rpt -pb Final_Project_utilization_synth.pb }
