# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.cache/wt [current_project]
set_property parent.project_path C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/imports/uart/data_sync.v
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/imports/uart/uart_tx.v
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/imports/uart/uart_rx.v
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/imports/uart/uart_baud_tick_gen.v
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/new/UART_RX_CTRL.v
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/imports/uart/uart_basic.v
  C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/sources_1/new/Slave_Endpoint_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Diego/LabDigitales2017/UART_RX_CTRL/UART_RX_CTRL.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}]


synth_design -top Slave_Endpoint_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Slave_Endpoint_top.dcp

catch { report_utilization -file Slave_Endpoint_top_utilization_synth.rpt -pb Slave_Endpoint_top_utilization_synth.pb }
