# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.cache/wt [current_project]
set_property parent.project_path C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.srcs/sources_1/imports/Downloads/clockuru.v
  C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.srcs/sources_1/imports/Lab6_PS2_VGA_reference/kbd_ms.v
  C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.srcs/sources_1/new/Lab6.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}
set_property used_in_implementation false [get_files {{C:/GitHub/LabDigitales2017/Lab6_PartePrevia/Lab6_PartePrevia.srcs/constrs_1/imports/LabDigitales2017/The Final Alcachofita.xdc}}]


synth_design -top Lab6 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Lab6.dcp

catch { report_utilization -file Lab6_utilization_synth.rpt -pb Lab6_utilization_synth.pb }
