# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.cache/wt [current_project]
set_property parent.project_path C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/imports/5.2.3/ssdec.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/imports/Downloads/unsigned_to_bcd.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/imports/new/pwm.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/imports/new/ejem_01.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/imports/Downloads/clockuru.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/new/ALU.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/imports/5.2.3/display.v
  C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/sources_1/new/No_ALU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Diego/Downloads/Lab4_PartePrevia/Lab4_PartePrevia.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]


synth_design -top lab_4 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab_4.dcp

catch { report_utilization -file lab_4_utilization_synth.rpt -pb lab_4_utilization_synth.pb }
