# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.cache/wt [current_project]
set_property parent.project_path C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/new/ALU.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/new/UART_RX_CTRL.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/new/UART_TX_CTRL.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/new/data_sync.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/new/decodificador_7s.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/new/driver_display7seg.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/Desktop/uart_basic.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/Desktop/uart_baud_tick_gen.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/new/uart_rx.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/Desktop/uart_tx.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/imports/Downloads/unsigned_to_bcd.v
  C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/sources_1/new/top_modulept2.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/GitHub/LabDigitales2017/LAB_5(gerson)/LAB_5.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]


synth_design -top top_modulept2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_modulept2.dcp

catch { report_utilization -file top_modulept2_utilization_synth.rpt -pb top_modulept2_utilization_synth.pb }
